import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.zinc.light.color,
///  style: FThemes.zinc.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.zinc.light.color,
///    style: FThemes.zinc.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/themes#customize-themes for more information.
FBottomNavigationBarStyle bottomNavigationBarStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FBottomNavigationBarStyle(
  decoration: BoxDecoration(
    border: Border(top: BorderSide(color: colors.border)),
    color: colors.background,
  ),
  itemStyle: _bottomNavigationBarItemStyle(
    colors: colors,
    typography: typography,
    style: style,
  ),
  padding: const EdgeInsets.all(5),
);

FBottomNavigationBarItemStyle _bottomNavigationBarItemStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FBottomNavigationBarItemStyle(
  iconStyle: FWidgetStateMap({
    WidgetState.selected: IconThemeData(color: colors.primary, size: 24),
    WidgetState.any: IconThemeData(
      color: colors.disable(colors.foreground),
      size: 24,
    ),
  }),
  textStyle: FWidgetStateMap({
    WidgetState.selected: typography.base.copyWith(
      color: colors.primary,
      fontSize: 10,
    ),
    WidgetState.any: typography.base.copyWith(
      color: colors.disable(colors.foreground),
      fontSize: 10,
    ),
  }),
  tappableStyle: style.tappableStyle,
  focusedOutlineStyle: style.focusedOutlineStyle,
  padding: const EdgeInsets.all(5),
  spacing: 2,
);
